model = "gpt-6.1-sol"
model_reasoning_effort = "high"
service_tier = "priority"
notify = [ "C:\\Users\\CGY\\AppData\\Local\\OpenAI\\Codex\\runtimes\\cua_node\\81ea4d5168ddd0a3\\bin\\node_modules\\@oai\\sky\\bin\\windows\\codex-computer-use.exe", "turn-ended" ]
[mcp_servers]

[mcp_servers.cua_repl]
command = 'C:\Program Files\WindowsApps\OpenAI.Codex_26.930.2377.0_x64__2p2nqsd0c76g0\app\ChatGPT.exe'
enabled = false

[mcp_servers.node_repl]
args = []
command = 'C:\Users\CGY\AppData\Local\OpenAI\Codex\runtimes\cua_node\81ea4d5168ddd0a3\bin\node_repl.exe'
env_vars = ["CODEX_WINDOWS_REGISTERED_CORE"]
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = 'C:\Users\CGY\AppData\Local\OpenAI\Codex\runtimes\cua_node\81ea4d5168ddd0a3\bin\node_modules'
NODE_REPL_NODE_PATH = 'C:\Users\CGY\AppData\Local\OpenAI\Codex\runtimes\cua_node\81ea4d5168ddd0a3\bin\node.exe'
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\CGY\.codex;C:\Users\CGY\AppData\Local\OpenAI\Codex\runtimes\cua_node\81ea4d5168ddd0a3\bin\node_modules'
CODEX_HOME = 'C:\Users\CGY\.codex'
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab,mcpapps"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.930.21537"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"C:/Users/CGY/.codex/plugins/cache/openai-bundled/browser/26.930.21537/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
SKY_CUA_NATIVE_PIPE = "1"
SKY_CUA_NATIVE_PIPE_DIRECTORY = '\\.\pipe\codex-computer-use-2e46ee6f-dd16-41fb-8ee7-a7755203ec5f'
CODEX_CLI_PATH = 'C:\Users\CGY\AppData\Local\OpenAI\Codex\bin\be3fd7e5c1969ff6\codex.exe'
NODE_REPL_UNTRUSTED_ENV_ALLOWLIST = "CODEX_WINDOWS_REGISTERED_CORE"

[desktop]
followUpQueueMode = "steer"
conversationDetailMode = "STEPS_COMMANDS"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = '\\?\C:\Users\CGY\.cache\codex-runtimes\codex-primary-runtime\plugins\openai-primary-runtime'

[marketplaces.openai-bundled]
source_type = "local"
source = '\\?\C:\Users\CGY\.codex\.tmp\bundled-marketplaces\openai-bundled'

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[windows]
sandbox = "elevated"

[projects.'c:\users\cgy\documents\codex\2026-09-21\1']
trust_level = "trusted"

[projects.'c:\users\cgy\documents\codex\2026-09-21\reversible-memory-internalization-for-personalized-llms']
trust_level = "trusted"

[projects.'d:\first_research']
trust_level = "trusted"

[projects.'c:\users\cgy\documents\chatgpt\new project']
trust_level = "trusted"

[projects.'d:\googlenet\agent']
trust_level = "trusted"

[projects.'d:\googlenet\agent2']
trust_level = "trusted"

[projects.'d:\math_question']
trust_level = "trusted"

[projects.'d:\googlenet']
trust_level = "trusted"

[projects.'c:\users\cgy\documents\codex\2026-09-27\ffor']
trust_level = "trusted"

[projects.'d:\googlenet\ai sichu']
trust_level = "trusted"

[projects.'d:\googlenet\langchain_course']
trust_level = "trusted"

[[skills.config]]
path = 'C:\Users\CGY\.codex\skills\review-cumcm-paper\SKILL.md'
enabled = false

[[skills.config]]
path = 'C:\Users\CGY\.codex\skills\math-modeling-contest-workflow\SKILL.md'
enabled = false
